---
name: ShowCoordinates
main: kim\present\showcoordinates\ShowCoordinates
version: 1.0.0
api: [4.0.0]
author: PresentKim
website: https://github.com/PresentKim/ShowCoordinates-PMMP
description: Implements showcoordinates of gamerule

permissions:
  gamerules.showcoordinates:
    description: /gamerules showcoordinates
    default: true
...