---
name: ShowCoordinates
main: kim\present\showcoordinates\ShowCoordinates
version: 1.0.1
api: [3.0.0, 3.0.0-ALPHA12, 4.0.0]
author: PresentKim
description: Implements showcoordinates of gamerule

permissions:
  gamerules.showcoordinates:
    description: /gamerules showcoordinates
    default: true
...